#!/bin/bash

SUBMARINER_USER=${SUBMARINER_USER:-$USER}
SUBMARINER_SERVER_IP=${SUBMARINER_SERVER_IP:-"10.8.125.32"}
SUBMARINER_BASE_DIRECTORY=${SUBMARINER_BASE_DIRECTORY:-"/home/${SUBMARINER_USER}/src/submariner-io"}
SUBMARINER_DIFF_FILENAME="submariner_patch.diff"
